version: "3.4"

services:
  redis:
    image: "redis:latest"
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    volumes:
      - dataredis:/usr/local/etc/redis/redis.conf
    networks:
      - backend
    sysctls:
      net.ipv4.ip_local_port_range: 49152 65535

  postgresql: 
    container_name:  postgres-db
    image: "postgres:latest"
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khong123
      POSTGRES_DB: server_bttt
    volumes:
     - pgdata:/var/lib/postgresql/data

  go:
    container_name: go
    build: 
      context: .
    networks:
      - backend
    depends_on:
      - "redis"
      - "postgresql"
    
networks:
  backend:
    driver: bridge

volumes:
  dataredis: 
  pgdata:

